name: Build and Release HyperTP

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Extract version from tag
      id: version
      run: |
        if [[ ${{ github.ref }} == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"

    - name: Build with Maven
      run: mvn -B clean package -DskipTests

    - name: Run tests
      run: mvn -B test

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: HyperTP ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/HyperTP-${{ steps.version.outputs.version }}.jar
        asset_name: HyperTP-${{ steps.version.outputs.version }}.jar
        asset_content_type: application/java-archive

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HyperTP-${{ steps.version.outputs.version }}
        path: target/HyperTP-*.jar
        retention-days: 90

    - name: Build Success Report
      run: |
        echo "🎉 HyperTP Build Successful!" >> $GITHUB_STEP_SUMMARY
        echo "============================" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version**: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "**Java**: 21" >> $GITHUB_STEP_SUMMARY  
        echo "**Minecraft**: 1.21-1.21.8" >> $GITHUB_STEP_SUMMARY
        echo "**Build Date**: $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## 📥 Download" >> $GITHUB_STEP_SUMMARY
        echo "JAR file is available in **Artifacts**" >> $GITHUB_STEP_SUMMARY
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "Also available in **Releases**" >> $GITHUB_STEP_SUMMARY
        fi
        
