name: Version Check

on:
  push:
    branches: [ main, master ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get version from pom.xml
      id: version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"

    - name: Check if version exists as release
      id: check-release
      run: |
        RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.version.outputs.version }}")
        if echo "$RESPONSE" | grep -q "Not Found"; then
          echo "is_new_version=true" >> $GITHUB_OUTPUT
        else
          echo "is_new_version=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Release on New Version
      if: steps.check-release.outputs.is_new_version == 'true'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: HyperTP v${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
